name: build
on: push
jobs:
  compile:
    name: Windows Win32 x86
    runs-on: windows-latest
    env:
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          vcpkg version
          vcpkg install --triplet x86-windows
      - name: CMake Generate
        shell: cmd
        run: |
          call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat" x86
          cmake --preset x86-msvc-relwithdebinfo -D3DMM_PACKAGE_WIX=OFF
      - name: CMake Build
        shell: cmd
        run: |
          call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat" x86
          cmake --build build/x86-msvc-relwithdebinfo --target dist
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: |
            build/x86-msvc-relwithdebinfo
            !build/x86-msvc-relwithdebinfo/_CPack_Packages
            !build/x86-msvc-relwithdebinfo/chomp/studio/*.chk
            !build/x86-msvc-relwithdebinfo/*.zip
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: 3DMMEx Release
          path: |
            build/x86-msvc-relwithdebinfo/*.zip
          compression-level: 0 # already compressed
